//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class @event {
    
    private items itemsField;
    
    private int totalNumberOfTestsField;
    
    private bool totalNumberOfTestsFieldSpecified;
    
    private suite suiteField;
    
    private test testField;
    
    private eventRun runField;
    
    private string typeField;
    
    /// <remarks/>
    public items items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    public int totalNumberOfTests {
        get {
            return this.totalNumberOfTestsField;
        }
        set {
            this.totalNumberOfTestsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalNumberOfTestsSpecified {
        get {
            return this.totalNumberOfTestsFieldSpecified;
        }
        set {
            this.totalNumberOfTestsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public suite suite {
        get {
            return this.suiteField;
        }
        set {
            this.suiteField = value;
        }
    }
    
    /// <remarks/>
    public test test {
        get {
            return this.testField;
        }
        set {
            this.testField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public eventRun run {
        get {
            return this.runField;
        }
        set {
            this.runField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class items {
    
    private suite[] suiteField;
    
    private test[] testField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("suite")]
    public suite[] suite {
        get {
            return this.suiteField;
        }
        set {
            this.suiteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("test")]
    public test[] test {
        get {
            return this.testField;
        }
        set {
            this.testField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class suite {
    
    private string nameField;
    
    private string descriptionField;
    
    private items itemsField;
    
    private System.DateTime startTimeField;
    
    private bool startTimeFieldSpecified;
    
    private System.DateTime endTimeField;
    
    private bool endTimeFieldSpecified;
    
    private decimal executionTimeField;
    
    private bool executionTimeFieldSpecified;
    
    private counter counterField;
    
    private string idField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public items items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime startTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startTimeSpecified {
        get {
            return this.startTimeFieldSpecified;
        }
        set {
            this.startTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime endTime {
        get {
            return this.endTimeField;
        }
        set {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endTimeSpecified {
        get {
            return this.endTimeFieldSpecified;
        }
        set {
            this.endTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal executionTime {
        get {
            return this.executionTimeField;
        }
        set {
            this.executionTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool executionTimeSpecified {
        get {
            return this.executionTimeFieldSpecified;
        }
        set {
            this.executionTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public counter counter {
        get {
            return this.counterField;
        }
        set {
            this.counterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class counter {
    
    private int disabledField;
    
    private int successField;
    
    private int failureField;
    
    private int errorField;
    
    private int warningField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int disabled {
        get {
            return this.disabledField;
        }
        set {
            this.disabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int success {
        get {
            return this.successField;
        }
        set {
            this.successField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int failure {
        get {
            return this.failureField;
        }
        set {
            this.failureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int warning {
        get {
            return this.warningField;
        }
        set {
            this.warningField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class test {
    
    private string executableTypeField;
    
    private string ownerNameField;
    
    private string objectNameField;
    
    private string procedureNameField;
    
    private bool disabledField;
    
    private bool disabledFieldSpecified;
    
    private string nameField;
    
    private string descriptionField;
    
    private int testNumberField;
    
    private bool testNumberFieldSpecified;
    
    private int totalNumberOfTestsField;
    
    private bool totalNumberOfTestsFieldSpecified;
    
    private System.DateTime startTimeField;
    
    private bool startTimeFieldSpecified;
    
    private System.DateTime endTimeField;
    
    private bool endTimeFieldSpecified;
    
    private decimal executionTimeField;
    
    private bool executionTimeFieldSpecified;
    
    private counter counterField;
    
    private string errorStackField;
    
    private testExpectation[] failedExpectationsField;
    
    private string idField;
    
    /// <remarks/>
    public string executableType {
        get {
            return this.executableTypeField;
        }
        set {
            this.executableTypeField = value;
        }
    }
    
    /// <remarks/>
    public string ownerName {
        get {
            return this.ownerNameField;
        }
        set {
            this.ownerNameField = value;
        }
    }
    
    /// <remarks/>
    public string objectName {
        get {
            return this.objectNameField;
        }
        set {
            this.objectNameField = value;
        }
    }
    
    /// <remarks/>
    public string procedureName {
        get {
            return this.procedureNameField;
        }
        set {
            this.procedureNameField = value;
        }
    }
    
    /// <remarks/>
    public bool disabled {
        get {
            return this.disabledField;
        }
        set {
            this.disabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool disabledSpecified {
        get {
            return this.disabledFieldSpecified;
        }
        set {
            this.disabledFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public int testNumber {
        get {
            return this.testNumberField;
        }
        set {
            this.testNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool testNumberSpecified {
        get {
            return this.testNumberFieldSpecified;
        }
        set {
            this.testNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int totalNumberOfTests {
        get {
            return this.totalNumberOfTestsField;
        }
        set {
            this.totalNumberOfTestsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalNumberOfTestsSpecified {
        get {
            return this.totalNumberOfTestsFieldSpecified;
        }
        set {
            this.totalNumberOfTestsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime startTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startTimeSpecified {
        get {
            return this.startTimeFieldSpecified;
        }
        set {
            this.startTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime endTime {
        get {
            return this.endTimeField;
        }
        set {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endTimeSpecified {
        get {
            return this.endTimeFieldSpecified;
        }
        set {
            this.endTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal executionTime {
        get {
            return this.executionTimeField;
        }
        set {
            this.executionTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool executionTimeSpecified {
        get {
            return this.executionTimeFieldSpecified;
        }
        set {
            this.executionTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public counter counter {
        get {
            return this.counterField;
        }
        set {
            this.counterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string errorStack {
        get {
            return this.errorStackField;
        }
        set {
            this.errorStackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("expectation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public testExpectation[] failedExpectations {
        get {
            return this.failedExpectationsField;
        }
        set {
            this.failedExpectationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class testExpectation {
    
    private string messageField;
    
    private string callerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string caller {
        get {
            return this.callerField;
        }
        set {
            this.callerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class eventRun {
    
    private System.DateTime startTimeField;
    
    private System.DateTime endTimeField;
    
    private decimal executionTimeField;
    
    private counter counterField;
    
    /// <remarks/>
    public System.DateTime startTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime endTime {
        get {
            return this.endTimeField;
        }
        set {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    public decimal executionTime {
        get {
            return this.executionTimeField;
        }
        set {
            this.executionTimeField = value;
        }
    }
    
    /// <remarks/>
    public counter counter {
        get {
            return this.counterField;
        }
        set {
            this.counterField = value;
        }
    }
}
